name: PMD Static Code Analysis
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'ruleset.xml'
        analyzeModifiedFilesOnly: false
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: pmd-report.sarif
